# Generated by Django 2.0.2 on 2018-02-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('session_id', models.IntegerField(default=0)),
                ('error', models.BooleanField(default=False)),
                ('message', models.TextField(max_length=2018)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('original_id', models.CharField(blank=True, max_length=255)),
                ('hash', models.CharField(max_length=32)),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('schema', models.CharField(max_length=32)),
                ('session_id', models.BigIntegerField(default=0)),
                ('create_date', models.DateTimeField(db_index=True)),
                ('update_date', models.DateTimeField(db_index=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('reset', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecordsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uri', models.TextField(max_length=2048)),
                ('format', models.CharField(choices=[('iso2709', 'iso2709')], default='iso2709', max_length=64)),
                ('schema', models.CharField(choices=[('rusmarc', 'rusmarc')], default='rusmarc', max_length=64)),
                ('encoding', models.CharField(default='utf-8', max_length=64)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvester.Source')),
            ],
        ),
        migrations.CreateModel(
            name='RecordContent',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='harvester.Record')),
                ('content', models.BinaryField(max_length=102400)),
            ],
        ),
        migrations.AddField(
            model_name='harvestingstatus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvester.Source'),
        ),
    ]
